language: scala
jdk: openjdk8

jobs:
   include:
     - stage: test
       script: sbt test
       name: Run all unit tests

stages:
  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
