---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - master
  pull_request:

jobs:
  checks:
    name: Format and style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: adopt:14
        apps: sbtn
    - run: sbtn scalafixAll --check
    - run: sbtn scalafmtCheckAll
    - run: sbtn scalafmtSbtCheck
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: laughedelic/coursier-setup@v1
      with:
        jvm: adopt:14
        apps: sbtn
    - run: sbtn test
